[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mathjson-solver"
version = "1.20.0"
authors = [{name = "Martins Mednis", email = "mrt@mednis.info"}]
description = "Utilities for MathJSON evaluation"
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/LongenesisLtd/mathjson-solver"
"Bug Tracker" = "https://github.com/LongenesisLtd/mathjson-solver/issues"
