name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pytest pytest-cov

      - name: Run Tests with Coverage
        run: |
          pytest --cov=mathjson_solver --cov-report=term-missing --cov-report=xml

      - name: Extract Coverage Percentage
        run: |
          COVERAGE=$(grep -oP '(?<=<coverage line-rate=")[0-9.]+(?=")' coverage.xml)
          COVERAGE_PERCENT=$(awk -v cov="$COVERAGE" 'BEGIN {print int(cov * 100)}')
          echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV

      - name: Generate Coverage Badge
        run: |
          COLOR="red"
          if [ $COVERAGE_PERCENT -ge 80 ]; then COLOR="green"; 
          elif [ $COVERAGE_PERCENT -ge 50 ]; then COLOR="yellow"; 
          fi
          echo "![Coverage](https://img.shields.io/badge/coverage-${COVERAGE_PERCENT}%25-${COLOR})" > coverage-badge.md

      - name: Commit and Push Badge
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add coverage-badge.md
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push
